name: Build Python

on:
  workflow_call:
    inputs:
      python_version:
        required: true
        type: string
      arch:
        required: true
        type: string

jobs:
  build_linux_zig:
    name: Linux ${{ inputs.python_version }} ${{ inputs.arch }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          sudo ./scripts/build_linux_zig.sh ${{ inputs.arch }} ${{ inputs.python_version }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: python
          path: ./python*.zip

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: build-python
          path: ./*python*.tar.gz